<?php

define('_DECONNEXION', 'Deconnexion');
define('_MENTION', 'Mention');
define('_ANCIENNE', 'Ancienne');
define('_NOUVELLE', 'Nouveau');
define('_CLIENT', 'Client');
define('_SITAUTION', 'Situation');
define('_REEL', 'R�el');
define('_PREVISIONNEL', 'Previsionnel');
define('_RAISON', 'Raison');
define('_SOCIAL', 'Social');
define('_GSM', 'GSM');
define('_FIX', 'Fix');
define('_COMMERCIAL', 'Commercial');
define('_POST', 'Post');
define('_MODULE', 'Module');
define('_PU', 'P.U');
define('_RECHERCHER', 'Rechercher');
define('_TABLEAU', 'Tableau');
define('_RAPPORTS', 'Rapports');
define('_CLIENTS', 'Client(s)');
define('_COMMENDER', 'Commender');
define('_COMMANDES', 'Commandes');
define('_DEBITEURS', 'Debiteurs');
define('_POURCENTAGE', 'pourcentage');
define('_FONCTIONNALITES', 'Fonctionnalit�s');
define('_MODULES', 'Modules');
define('_SUIVIS', 'Suivis');
define('_COMMERCIAUX', 'Commerciaux');
define('_CONTACTS', 'Contacts');
define('_REGLEMENTS', 'R�glements');
define('_REGLER', 'R�gler');
define('_COMPTABILITES', 'Comptabilit�(s)');
define('_APPELS', 'Appel T�l�phonique');
define('_DEPLACEMENTS', 'D�placement');
define('_REMARQUE', 'Remarque');
define('_COUT', 'Co�t');
define('_FACTURE', 'Facture');
define('_NBRFONCTIONNALITE', 'Nombre Fonctionnalit�es	');
define('_VERSION', '&copy; 2010 - (18/05/2010)');
define('_QUITTER', 'Quitter');
define('_PARAM', 'Param�trage(s)');
define('_AJOUTER', 'Ajouter');
define('_MODIFIER', 'Mettre � jour');
define('_SUPPRIMER', 'Supprimer');
define('_OP', 'Op&eacute;ration(s)');
define('_LISTE', 'Liste');
define('_CONNEXION', 'Connexion');
define('_NOM', 'Name');
define('_PRENOM', 'Pr�nom');
define('_EMAIL', 'Email');
define('_NB', 'Nombre');
define('_LOGIN', 'E-mail');
define('_PASSWORD', 'Code confidentiel');
define('_FACTURES', 'Factures');
define('_VIDE', '<div class="alert"><button class="close" data-dismiss="alert">�</button><div class="center-warning">El�ments de donn�es vide !</div></div>');
define('_MENU_ADMIN', 'Menu admin.');
define('_CATEGORIES', 'Cat�gorie(s)');
define('_CARACTERISTIQUES', 'Caract�ristique(s)');
define('_LIBELLE', 'Libell�');
define('_ENVOYER', 'Envoyer');
define('_LISTES', 'Liste(s)');
define('_CHAINE', 'Chaine');
define('_VILLE', 'Ville');
define('_CONTRAT', 'Contrat');
define('_ETAT', 'Etat');
define('_RECHERCHE', 'Recherche');
define('_TYPE', 'Type');
define('_VALEUR', 'Valeur');
define('_SOCIETE', 'Soci�t�');
define('_PAYS', 'Pays');
define('_QUARTIER', 'Quartier');
define('_ADRESSE', 'Adresse');
define('_IMAGE', 'Image');
define('_CLASSIFICATION', 'Classification');
define('_RC', 'Registre de Commerce');
define('_PATENTE', 'Patente');
define('HEURE', 'Heure');
define('DEPART', 'D�part');

//Les messages
define('_AJOUT_OK', 'L\'ajout a �t� effectu� avec succ�s.');
define('_AJOUT_NOK', 'L\'ajout a �chou� !');
define('_SUPPRESSION_OK', 'Suppression �ffectu�e avec succes');
define('_SUPPRESSION_NOK', 'Suppression a �chou�e !');
define('_MODIFICATION_OK', 'Modification effectu�e avec succ�s');
define('_MODIFICATION_NOK', 'Erreur lors de la modification !');
define('_ERREUR_LOGIN', 'Param�tes de connexion incorrects !');
define('_ERREUR_PROFIL', 'Votre profil est incomplet, veuillez contacter votre administrateur !');
//Fin Messages

define('_DESC', 'Description');
define('_PHOTOS', 'Photos');
define('_MENU', 'Menu');
define('_CHAMBRES', 'Chambre(s)');
define('_TITRE', 'Titre');
define('_REDIRECT', 'Veuillez patienter ...');
define('_TEL', 'Tel.');
define('_FAX', 'Fax');
define('_MODIFICATION', 'Modification');
define('_COMPTABILITE', 'Comptabilit�');
define('_ADMINISTRATION', 'Administration.');
define('_FICHES', 'Fiche(s)');
define('_HISTORIQUE', 'Historique');
define('_FILTRE', 'Filtre');
define('_UTILISATEURS', 'Utilisateur(s)');
define('_INFOS_GENERALES', 'Infos. G�n�rales');
define('_LOCALISATION', 'Localisation');
;
define('_GALERIE', 'Galerie d\'images');
define('_DELAI', 'Delai');
define('_ANNULATION', 'Annulation');
define('_SECRETAIRE', 'Secretaire(s)');
define('_PARTENAIRE', 'Partenaire(s)');
define('_TABLES', 'Table(s)');
define('_JOURS', 'Jour(s)');
define('_DESCRIPTION', 'Description');
define('_LEGENDE', 'Legende');
define('_NOMBRE', 'Nb.');
define('_DEPART', 'D�part');
define('_ETATS', 'Etat');
define('_MONTANT', 'Montant');
define('_PERIODE', 'P�riode');
define('_TARIFS', 'Tarif(s)');
define('_PENSION', 'Pension');
define('_DEFINIR', 'Definir');
define('_GESTION', 'Gestion');
define('_VALIDER', 'Valider');
define('_DATE', 'Date');
define('_DEBUT', 'Debut');
define('_FIN', 'Fin');
define('_L', 'L');
define('_M', 'M');
define('_J', 'J');
define('_V', 'V');
define('_S', 'S');
define('_D', 'D');
define('_JANVIER', 'Janvier');
define('_FEVRIER', 'Fevrier');
define('_MARS', 'Mars');
define('_AVRIL', 'Avril');
define('_MAI', 'Mai');
define('_JUIN', 'Juin');
define('_JUILLET', 'Juillet');
define('_AOUT', 'A�ut');
define('_SEPTEMBRE', 'Septembre');
define('_OCTOBRE', 'Octobre');
define('_NOVEMBRE', 'Novembre');
define('_DECEMBRE', 'Decembre');
define('_LUNDI', 'Lundi');
define('_MARDI', 'Mardi');
define('_MERCREDI', 'Mercredi');
define('_JEUDI', 'Jeudi');
define('_VENDREDI', 'Vendredi');
define('_SAMEDI', 'Samedi');
define('_DIMANCHE', 'Dimanche');
define('_CODES', 'Codes');
define('_ACCES', 'Acc�s');
define('_PAYS_VILLE', 'Pays - Ville');
define('_INFO_BANQUAIRE', 'Coordonn�e(s) Banquaire(s)');
define('_CONFIRMER', 'Confirmer');
define('_ANNULER', 'Annuler');
define('_DETAILS', 'D�tails');
define('_DESTINATIONS', 'Destinations');
define('_MENU_ANNEXE', 'Menu Annexe');
define('_DEVENIR', 'Devenir');
define('_CONTACT', 'Contact');
define('_ACCUEIL', 'Accueil');
define('_INDICATION', 'Les champs marqu�s en (*) sont obligatoires !');
define('_RECHERCHE_DETAILLEE', 'Recherche d�taill�e');
define('_PERSONNES', 'Personne(s)');
define('_COMPTE', 'Compte');
define('_ADMIN', 'Admin.');
define('_SUPPRIMEES', 'Supprim�(es)');
define('_EMAIL_EXISTANT', 'Adresse Email Existante !');
define('_AJOUT', 'Ajout');
define('_SUPPRESSION', 'Suppression');
define('_TABLE', 'Table');
define('_INITIALISER', 'Initialiser(s)');
define('_ACTUEL', 'Actuel');
define('_CREER', 'Cr�er');
define('_NEW', 'Nouveau');
define('_RETAPER', 'Retaper');
define('_ANCIEN', 'Ancien');
define('_TOUT', 'Tout');
define('_AFFICHER', 'Afficher');
define('_DUREE', 'Dur�e');
define('_ASSOCIER', 'Associer');
define('_ANNEES', 'Ann�e(s)');
define('_MOIS', 'Mois');
define('_SUIVANT', 'Suivant');
define('_TRI', 'Tri');
define('_DATES', 'Date(s)');
define('_ENTRE', 'Entre');
define('_ET', 'et');
define('_ENVOI_OK', 'Message envoy� avec succes');
define('_ENVOI_NOK', 'Message non envoy� !');
define('_STATS', 'Statistiques');
define('_PUBLIQUE', 'Publique');
define('_FICHE', 'Fiche');
define('_NUITS', 'nuit(s)');
define('_TOTAL', 'Total');
define('_TOTAUX', 'Totaux');
define('_COORDONNEES', 'Coordonn�es');
define('_MOBILE', 'Mobile');
define('_COMISSION', 'Comission');
define('_INITIALISATION', 'Initialisation ');
define('_ETAPE', '�tape');
define('_COMMENTAIRES', 'Commentaires');
define('_CODE_POSTAL', 'Code postal');
define('_CIVILITE', 'Civilit�');
define('_BANQUE', 'Banque');
define('_DESIGNATION', 'D�signation');
define('_IMPRIMER', 'Imprimer');
define('_ENTITE', 'Entit�');
define('_EN_COURS_VALIDATION', 'En cours de validation');
define('_ACCEPTEE', 'Accept�e');
define('_REFUSEE', 'Refus�e');
define('_ANNEES_SCOLAIRES', 'Ann�e(s) scolaire(s)');
define('_CYCLES', 'Cycle(s)');
define('_NIVEAUX', 'Niveau(x)');
define('_GROUPES', 'Groupe(s)');
define('_TESTS', 'Test(s)');
define('_FRAIS', 'Frais');
define('_SCOLARITE', 'Scolarit�');
define('_SALLES', 'Salle(s)');
define('_TRANSPORT', 'Transport');
define('_GARDE', 'Garde');
define('_MATIERES', 'Mati�re(s)');
define('_ENTREE', 'Entr�e');
define('_DOSSIERS', 'Dossier(s)');
define('_INSCRIPTION', 'Inscription(s)');
define('_INSCRIPTION2', 'Inscr.');
define('_PIECES', 'Pi�ce(s)');
define('_COMMUNES', 'Commune(s)');
define('_SPECIFIQUES', 'Sp�cifique(s)');
define('_HEURE', 'Heure(s)');
define('_H', 'h');
define('_ELEVES', 'El�ve(s)');
define('_RENSEIGNEMENTS', 'Renseignement(s)');
define('_CNES', 'C.N.E');
define('_CNES2', 'Code National');
define('_SEXES', 'Sexe');
define('_NAISSANCES', 'Naissance');
define('_FRERES', 'Fr�re(s)');
define('_SOEURS', 'Soeur(s)');
define('_DOMICILES', 'Domicile(s)');
define('_TELEPHONE', 'T�l�phone');
define('_PROFESSION', 'Profession');
define('_PARENTS', 'Parent(s)');
define('_URGENCES', 'Urgence');
define('_PERE', 'P�re(s)');
define('_MERE', 'M�re(s)');
define('_MALADIES', 'Maladie(s)');
define('_DIFFICULTES', 'Difficult�(s)');
define('_DIFFICULTES_SCOLAIRES', 'Difficult�(s) scolaire(s)');
define('_HORAIRES', 'Horaire(s)');
define('_FEMININ', 'Gar�on');
define('_MASCULIN', 'Fille');
define('_MEDECINS', 'M�decin(s)');
define('_ACTIVES', 'Active(s)');
define('_PREINSCRIPTION', 'Pr�-inscription(s)');
define('_NOTES', 'Note(s)');
define('_RESULTATS', 'Resultat(s)');
define('_INSCRIPTIONS', 'Inscription(s)');
define('_PERSONNEL', 'Personnel');
define('_SITE', 'Site Web');
define('_OBLIGATOIRES', 'Oblig.');
define('_NON_DEFINIE', 'Non d�finie !');
define('_PLAN', 'Plan');
define('_ELEMENTS', 'Element(s)');
define('_LIENS', 'Lien(s)');
define('_MENUS', 'Menu(s)');
define('_URL', 'URL');
define('_PROFILS', 'Profil(s)');
define('_DROITS', 'Droit(s)');
define('_PAGE_DEFAUT', 'Page par defaut');
define('_ERREUR_PARAM', 'Erreur de param�trage, veuillez contacter votre administrateur !');
define('_DEVISE', 'DH');
define('_OBLIGATOIRE', 'Oblig.');
define('_DECISIONS', 'D�sicions');
define('_MOTIFS', 'Motif(s)');
define('_OPTION', 'En option');
define('_ACCEPTE', 'Accept�');
define('_REJETE', 'Rejet�');
define('_REJETEES', 'Rejet�e(s)');
define('_TYPES', 'Type(s)');
define('_MENSUEL', 'Mensuel');
define('_TRIMESTRIEL', 'Trimestriel');
define('_ANNUEL', 'Annuel');
define('_REDUCTIONS', 'R�duction(s)');
define('_ORDRE', 'Ordre');
define('_RECETTE', 'Recette(s)');
define('_DEPENSES', 'D�pense(s)');
define('_PREVISIONNELLES', 'Pr�visionnelle(s)');
define('_EFFECTIVES', 'Effective(s)');
define('_IMPAYES', 'Impay�(es)');
define('_PAGE', 'Page');
define('_DEFINITIONS', 'D�finition(s)');
define('_ETABLISSEMENT', 'Mon �tablissement');
define('_WEB', 'Site(s) Web');
define('_NOUVEAU', 'Nouveau');
define('_RETAPEZ', 'Retaper');
define('_CODE', 'Code');
define('_DEFINIR_ANNEE_ACTIVE', 'Veuillez d�finir l\'ann�e en cours !');
define('_SYSTEMES', 'Syst�me(s)');
define('_HEAD', 'Head');
define('_FOOT', 'Foot');
define('_CONN', 'conn.');
define('_MESSAGE_DECISIONS', 'Veuillez mettre � jour la d�cision concernant cet �l�ve pour pouvoir activer l\'inscription');
define('_VILLES', 'Ville(s)');
define('_PHOTO', 'Photo');
define('_CAISSE', 'Caisse');
define('_JOURNAL', 'Journal');
define('_ACTIONS', 'Action(s)');
define('_CONNEXIONS', 'Connexion(s)');
define('_STATISTIQUES', 'Statistique(s)');
define('_ERREUR_PREINSCRIPTION', 'Les pr�inscriptions en attente');
define('_DERNIERES', 'Derni�re(s)');
define('_COMMUNS', 'Commun(s)');
define('_INCOMPLET', 'Incomplet(s)');
define('_REDUCTION', 'R�duction(s)');
define('_ANNUELLE', 'Annuelle(s)');
define('_ENCAISSER', 'Encaisser');
define('_DERNIERS', 'Dernier(s)');
define('_ENCAISSEMENTS', 'Encaissement(s)');
define('_RETARDATAIRES', 'Retardataire(s)');
define('_NATURES', 'Nature(s)');
define('_FOURNISSEURS', 'Fournisseur(s)');
define('_RAISONS', 'Raison(s)');
define('_SOCIALES', 'Sociale(s)');
define('_IMPORTER', 'Importer');
define('_IMPORTES', 'Import�(s)');
define('_NON_IMPORTES', 'Non Import�(s)');
define('_FICHIER', 'Fichier');
define('_CSV', 'CSV');
define('_EN_ATTENTE', 'En attente');
define('_TRANSPORTS', 'Transport(s)');
define('_TRAJETS', 'Trajet(s)');
define('_PRIX', 'Prix');
define('_FINANCE', 'Finance');
define('_BANQUES', 'Banque(s)');
define('_CAISSES', 'Caisse(s)');
define('_COMPTES', 'Compte(s)');
define('_MODE', 'Mode');
define('_DOCUMENT', 'Document');
define('_DOCUMENTS', 'Document(s)');
define('_N', 'N�');
define('_CHEQUES', 'Ch�que(s)');
define('_ESPECES', 'Esp�ce');
define('_VIREMENT', 'Virement bancaire');
define('_INITIAL', 'Initial');
define('_RIB', 'R.I.B');
define('_VISUALISER', 'Visualiser');
define('_FILTRES', 'Filtre(s)');
define('_ERREUR_DROITS', '<div class="erreur">Vous n\'�tes pas autoris� � visualiser cette page !</div>');
define('_ENCAISSEMENT', 'Encaissement');
define('_JOURNALIERES', 'Journali�re(s)');
define('_MENSUELLES', 'Mensuelle(s)');
define('_ANNUELLES', 'Annuelle(s)');
define('_ETABLISSEMENTS', 'Etablissement(s)');
define('_PREINSCRIPTIONS', 'Pr�inscription(s)');
define('_PERSONNELS', 'Personnel(s)');
define('_TRACES', 'Trace(s)');
define('_ORDRES', 'Ordre(s)');
define('_STAT', 'Statistique(s)');
define('_SCOLAIRES', 'Scolaire(s)');
define('_INSCRIPTION_REJETEE', 'La demande d\'inscription de cet �l�ve � �t� rejet�e pour les motifs pr�sent�s ci-apr�s :');
define('_REGLE', 'R�gl�');
define('_RESTE', 'Reste');
define('_IMPRESSION', 'Impression');
define('_WORD', 'Word');
define('_EXCEL', 'Excel');
define('_PARENTES', 'Parent�(s)');
define('_FI', 'F.I');
define('_FS', 'F.S');
define('_WARNING_REDUCTION', 'La r�duction n\'est plus param�trable car l\'�l�ve � d�j� r�gl� un mois de scolarite !');
define('_ALIMENTATIONS', 'Alimentation(s)');
define('_VIREMENTS', 'Virement(s)');
define('_SOURCE', 'Source');
define('_DESTINATION', 'Destination');
define('_PROPRIETAIRE', 'Propritaire');
define('_POSTES', 'Poste(s)');
define('_RS', 'R.S');
define('_PRODUITS', 'Produit(s)');
define('_SERVICES', 'Service(s)');
define('_CANTINE', 'Cantine');
define('_SUPPLEMENT', 'Suppl�ment(s)');
define('_PREMIER', 'Premier');
define('_DEF_MOIS_OBLIGATOIRES', 'Les mois dont le r�gelement est obligatoire au moment de l\'inscription');
define('_DEF_MOIS_SCOLARITE', 'Les mois de scolarit�');
define('_DEF_PREMIER', 'Le premier mois de l\'ann�e scolaires');
define('_DEF_DOCUMENT', 'Ch�que ou ordre de virement...');
define('_ECHEANCE', 'Ech�ance');
define('_POSTE', 'Poste');
define('_REMISES', 'Remise(s)');
define('_REMISE', 'Remise');
define('_RECU', 'Re�u');
define('_RECUS', 'Re�u(s)');
define('_CHEQUE', 'Ch�que');
define('_DCHEQUE', 'Date_Ch�que');
define('_SITUATION', 'Situation');
define('_FINANCIERE', 'Financi�re');
define('_PREINSCRIPTION_REQUISE', 'Une pr�inscription est requise !');
define('_FAMILLES', 'Famille(s)');
define('_REFERENCE', 'R�f�rence');
define('_REF', 'Ref.');
define('_PEREMPTION', 'P�remption');
define('_EXISTANTS', 'Existant(s)');
define('_EXISTANTES', 'Existante(s)');
define('_STOCK', 'Stock');
define('_TAUX', 'Taux');
define('_TVA', 'T.V.A');
define('_HT', 'H.T');
define('_TTC', 'T.T.C');
define('_QTE', 'Qte');
define('_COMMANDER', 'Commander');
define('_DEVIS', 'Devis');
define('_VALIDE', 'Valid�');
define('_FACTURER', 'Facturer');
define('_FACTUREE', 'Factur�(e)');
define('_CLOTURER', 'Cloturer');
define('_VEHICULES', 'V�hicule(s)');
define('_ASSURANCE', 'Assurance');
define('_ACTIVER', 'Activer');
define('_HEURES', 'Heure');
define('_MINUTES', 'Minutes');
define('_MENSUALITE', 'Mensualit�');
define('_POINTS', 'Point(s)');
define('_MENSUELS', 'Mensuel(s)');
define('_PASSAGE', 'Passage');
define('_CMD', 'Command�(es)');
define('_CSM', 'Consomm�(es)');
define('_POURCENT', 'Poucent. %');
define('_CLUBS', 'Club Sportif');
define('_MANUELS', 'Manuel(s)');
define('_ANNUELS', 'Annuel(s)');
define('_MARQUES', 'Marque(s)');
define('_MODELES', 'Mod�le(s)');
define('_IMMATRICULATION', 'Immatriculation');
define('_QUANTITE', 'Quantit�');
define('_VENDUS', 'Vendu(s)');
define('_MATIN', 'Matin');
define('_SOIR', 'Apr�s midi');
define('_RETOUR', 'Retour');
define('_ALLER', 'Aller');
define('_ARCHIVES', 'Archive(s)');
define('_ACTIVE', 'Activ�');
define('_DESACTIVER', 'D�sactiver');
define('_VEUILLEZ_SPECIFIER_MONTANT', 'Veuillez sp�cifier un montant sup�rieur � 0 !');
define('_RED', 'Red.');
define('_SUPPL', 'Suppl.');
define('_A', '�');
define('_SUPERIEUR', 'Sup�rieur');
define('_INFERIEUR', 'Inf�rieur');
define('_NON_REMIS', 'Non remis');
define('_REMIS', 'Remis');
define('_IMPAYE', 'Impay� !');
define('_1', '1');
define('_2', '2');
define('_CANTINES', 'Cantine');
define('_VEUILLEZ', 'Veuillez');
define('_SPECIFIER', 'sp�cifier');
define('_LES', 'Le(s)');
define('_LE', 'le');
define('_LA', 'la');
define('_DE', 'de');
define('_ACTIVATION', 'Activation');
define('_MESSAGES', 'Message(s)');
define('_ENVOYES', 'Envoy�(s)');
define('_SOLDE', 'Solde');
define('_FOURNITURES', 'Fourniture(s)');
define('_RECEPTION', 'Rec�ption');
define('_BOITE', 'Bo�te');
define('_DESTINATAIRES', 'Destinataire(s)');
define('_NON', 'Non');
define('_LUS', 'Lu(s)');
define('_NOUVEAUX', 'Nouveau(x)');
define('_EXPEDITEURS', 'Exp�diteur(s)');
define('_LU', 'Lu');
define('_JOINTES', 'Jointe(s)');
define('_BROUILLONS', 'Brouillons');
define('_MESSAGERIE', 'Messagerie');
define('_NON_ACTIVE', 'Non activ�');
define('_RESTES', 'Reste(s)');
define('_INSUFFISANT', 'Insuffisant');
define('_VEUILLEZ_AJOUTER_ALIMENTATION', 'Veuillez ajouter une alimentation de solde !');
define('_F', 'Fr.');
define('_MOTIF', 'Motif');
define('_SEUIL', 'Seuil');
define('_CONSOMMATIONS', 'Consommation(s)');
define('_ATTENTE', 'Attente');
define('_COCHER', 'Cocher');
define('_FICHIERS', 'Fichier(s)');
define('_LECTURE', 'Lecture');
define('_ENCAISSE', 'Encaiss�');
define('_NON_ENCAISSE', 'Non encaiss�');
define('_A_PAYER', '� payer');
define('_RUBRIQUES', 'Rubrique(s)');
define('_ENTREES', 'Entr�e(s)');
define('_SORTIES', 'Sortie(s)');
define('_UNITAIRE', 'unitaire');
define('_COMMANDE', 'Command�');
define('_OUVERT', 'Ouvert');
define('_CLOTURE', 'Cl�tur�');
define('_LIVREE', 'Livr�e');
define('_LIVRAISON', 'Livraison');
define('_DEPARTS', 'D�part(s)');
define('_JUSQU_A', 'Jusqu\'�');
define('_MESSAGE_DEPART_ELEVE', 'Cet �l�ve � quitt� l\'�cole');
define('_BANCAIRE', 'Bancaire');
define('_REMARQUES', 'Remarque(s)');
define('_PRELEVEMENTS', 'Pr�l�vement(s)');
define('_LIVREES', 'Livr�e(s)');
define('_COMMANDEES', 'Command�e(s)');
define('_RUPTURE', 'Rupture');
define('_CMP', 'C.M.P');
define('_CRENEAUX', 'Cr�neau(x)');
define('_LIVRAISONS', 'Livraison(s)');
define('_BL', 'B.L');
define('_ARTICLES', 'Article(s)');
define('_MOYENNE', 'Moyenne');
define('_MOYENNE2', 'Moy.');
define('_COEFFICIENT', 'Coefficient');
define('_COEF', 'Coef.');
define('_ABREVIATION', 'Abreviation');
define('_ADMIS', 'Admis(e)');
define('_NON_ADMIS', 'Non admis(e)');
define('_PLANNING', 'Planning');
define('_INDISPONIBLE', 'Indisponible');
define('_DEFINIR_PLANING', 'Veuillez d�finir le planning de ce test !');
define('_UTILES', 'Utile(s)');
define('_BULLETINS', 'Bulletin(s)');
define('_UNITES', 'Unit�(s)');
define('_DISCIPLINES', 'Discipline(s)');
define('_PEDAGOGIE', 'P�dagogie');
define('_SESSIONS', 'Session(s)');
define('_CONTROLES', 'Contr�le(s)');
define('_EXAMENS', 'Examen(s)');
define('_SEMESTRES', 'Semestre(s)');
define('_REGISTRES', 'Registre(s)');
define('_REG', 'Reg.');
define('_ENSEIGNANTS', 'Enseignant(s)');
define('_REPONDRE', 'R�pondre');
define('_ARCHIVER', 'Archiver');
define('_SAISIE', 'Saisie');
define('_DEFINIR_SEMESTRE_EN_COURS', 'Veuillez d�finir un semestre en cours !');
define('_PROF', 'Prof.');
define('_ENS', 'Ensg.');
define('_AGENTS', 'Agent(s)');
define('_AUCUN_MODELES', 'Veuillez d�finir un mod�le !');
define('_DEFINIR_UNITES_SCOLAIRES', 'Veuillez d�finir des unit�s scolaires !');
define('_DEFINIR_DISCIPLINES', 'Veuillez d�finir des disciplines !');
define('_DEFINIR_SEMESTRE', 'Veuillez d�finir des semestres !');
define('_DEFINIR_SESSIONS', 'Veuillez d�finir des sessions !');
define('_DEFINIR_CONTROLES', 'Veuillez d�finir des contr�les !');
define('_DEFINIR_MODELES', 'Veuillez d�finir des mod�les de registre des notes !');
define('_TMP', 'tmp');
define('_RELANCE', 'Relance');
define('_RACCOURCIS', 'raccourcis');
define('_DESCRIPTIF', 'Descriptif');
define('_RAPIDE', 'Rapide');
define('_REINS', 'Reins.');
define('_ERREUR_ACTIVATION_REINSCRIPTION', 'Veuillez contacter votre administrateur pour activer les r�inscription !');
define('_REINSCRIPTIONS', 'R�inscription(s)');
define('_ERREUR_DEFINITION_CYCLES', 'Veuillez contacter votre administrateur pour D�finir des cycles pour l\'ann�e de r�inscription !');
define('_ERREUR_DEFINITION_NIVEAUX', 'Veuillez contacter votre administrateur pour D�finir des niveaux pour l\'ann�e de r�inscription !');
define('_ERREUR_DEFINITION_GROUPES', 'Veuillez contacter votre administrateur pour D�finir des groupes pour l\'ann�e de r�inscription !');
define('_CA', 'C.A');
define('_SPECIFIER_NIVEAU_ANNEE', 'Veuillez sp�cifier un niveau et une ann�e scolaire !');
define('_AUTRES', 'Autre(s)');
define('_VEUILLEZ_DEFINIR_PARENTS', 'Veuillez d�finir un parent !');
define('_PROFESSEURS', 'professeurs');
define('_FERIES', 'feries');
define('_NUMERO', 'numero');
define('_GLOBALES', 'globale');
define('_EXTERIEURS', 'exterieurs');
define('_AUTEURS', 'auteurs');
define('_EDITEURS', 'editeurs');
define('_GENRES', 'genres');
define('_FORMATS', 'format');
define('_LIVRES', 'livres');
define('_BOBLIOTIQUE', 'bibliotique');
define('_ISBN', 'isbn');
define('_ABONNEE', 'abonnee');
define('_INFORMATIONS', 'informations');
?>